# Setup
title:               'Jane Doe / Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://appdev-projects.github.io/'
baseurl:             'til/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jane Doe
  url:               janedoe.com
  email:             hi@janedoe.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
